language: python
python:
    - "2.7"
sudo: required
install:
    - pip install -r requirements.txt
    - pip install pycodestyle
    - pip install coveralls
    - pip install codecov
script:
    - find ./groupCommunication -name \*.py -exec pycodestyle {} +
    - nosetests -vx --with-coverage --cover-erase --cover-package=GroupCommunication
after_success:
    - coveralls
    - codecov
notifications:
    email: false
